# Generated by Django 5.1.2 on 2024-11-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
